config/routes.rb
Rails.application.routes.draw do
  get '/players/available', to: 'players#available'

  resources :players

  resources :teams

  resources :results
  get '/results/round/:round', to: 'results#round'
  post 'results/draft', to: 'results#draft'

  root 'welcome#index'

end

app/models/draft.rb
class Draft < ActiveRecord::Base
  belongs_to :team
  belongs_to :player

  validates :round, :pick, :team_id, presence: true

  def self.max_round
    Draft.maximum("round")
  end

  def self.next_team
    if Draft.next_draft.nil?
      return nil
    else
      Draft.next_draft.team
    end
  end

  def self.next_draft
    Draft.where(player_id: nil).first
  end

  def self.draft(player_id)
    draft = Draft.next_draft

    draft.player = Player.find(player_id)
    draft.save!
  end

  def self.complete
    Draft.where('player_id IS NOT NULL').sort_by{:id}
  end

  def self.in_progress
    Draft.where(player_id: nil).sort_by{:id}
  end

  def complete?
    self.player.nil? ? false : true
  end

  def self.last_three
    Draft.complete.last(3)
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_one :draft
  has_one :team, through: :draft

  validates :name, :position, presence: true

  def self.available
    Player.all.select { |player| player.team.nil? }
  end

  def last_name
    self.name.split(' ')[1]
  end

  def drafted?
    self.team.nil? ? false : true
  end

  def self.random_available_player
    Player.available.sample
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :drafts
  has_many :players, through: :drafts

  validates :name, :division, presence: true

  def self.translate name
    translator = {'NY Giants': 'New York Giants', 'NY Jets': 'New York Jets'}
    translator[name].nil? ? name : translator[name]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all.sort_by{ |x| [x.position, x.last_name] }
  end

  def available
    @available = Player.available.sort_by{ |x| [x.position, x.last_name] }
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @drafts = Draft.all
    @last_three = Draft.last_three
  end

  def draft
    if request.post?
      Draft.draft(params[:player_id])
      redirect_to players_path
    end
  end

  def round
    @last_three = Draft.last_three
    @drafts = Draft.where(round: params[:round])

    if @drafts.empty?
      redirect_to results_path
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
    @players = @team.players
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">NFL Draft</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= "active" if current_page?(root_path) %>">
          <%= link_to "Home", root_path %>
        </li>
        <li class="<%= "active" if params[:controller] == "teams" %>">
          <%= link_to "Teams", teams_path %>
        </li>
        <li class="dropdown <%= "active" if current_page?(players_path) || current_page?(players_available_path) %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Players <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "All Players", players_path %></li>
            <li><%= link_to "Available Players", players_available_path %></li>
            <%# <li class="divider"></li> %>
          </ul>
        </li>

        <%# Results Dropdown %>
        <li class="dropdown <%= "active" if params[:controller] == "results" %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Results <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Full Results", results_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Round 1", "/results/round/1" %></li>
            <li><%= link_to "Round 2", "/results/round/2" %></li>
            <li><%= link_to "Round 3", "/results/round/3" %></li>
            <li><%= link_to "Round 4", "/results/round/4" %></li>
            <li><%= link_to "Round 5", "/results/round/5" %></li>
            <li><%= link_to "Round 6", "/results/round/6" %></li>
            <li><%= link_to "Round 7", "/results/round/7" %></li>
          </ul>
        </li>

        <p class="navbar-text navbar-right">
          <% if Draft.next_team.nil? %>
            Draft complete!
          <% else %>
            Next team: <%= Draft.next_team.name %>
          <% end %>
        </p>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NFL Draft</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "layouts/nav" %>
    <%= yield %>
  </div>
</body>
</html>

app/views/players/available.html.erb
<h1>Available Players</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Team</th>
    </tr>
  </thead>
  <tbody>
    <% @available.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.position %></td>
        <td>
            <%= form_tag("/results/draft", method: "post") do %>
                <%= hidden_field_tag(:player_id, player.id) %>
                <% if Draft.next_team.nil? %>
                  Draft Over
                <% else %>
                  <%= submit_tag "Draft to #{Draft.next_team.name}",
                    :class => "btn btn-success btn-sm" %>
                <% end %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/index.html.erb
<h1>All Players</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Team</th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <% if player.drafted? %>
        <tr class="success">
      <% else %>
        <tr>
      <% end %>
        <td><%= player.name %></td>
        <td><%= player.position %></td>
        <td>
          <% if player.team.nil? %>
            <%= form_tag("/results/draft", method: "post") do %>
                <%= hidden_field_tag(:player_id, player.id) %>
                <% if Draft.next_team.nil? %>
                  Draft Over
                <% else %>
                  <%= submit_tag "Draft to #{Draft.next_team.name}",
                    :class => "btn btn-success btn-sm" %>
                <% end %>
            <% end %>
          <% else %>
            <%= link_to player.team.name, player.team %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/results/_last_three.html.erb
<h3>Last three picks</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Round</th>
      <th>Pick</th>
      <th>Team</th>
      <th>Player</th>
    </tr>
  </thead>
  <tbody>
    <% @last_three.each do |draft| %>
      <% if draft.complete? %>
        <tr class="success">
      <% else %>
        <tr>
      <% end %>
        <td><%= draft.round %></td>
        <td><%= draft.pick %></td>
        <td><%= link_to draft.team.name, draft.team %></td>
        <td>
          <% if draft.player.nil? %>
            <i>In progress</i>
          <% else %>
            <%= draft.player.name %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/results/index.html.erb
<h1>Results</h1>

<%= render "results/last_three" %>

<h3>Full Results</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Round</th>
      <th>Pick</th>
      <th>Team</th>
      <th>Player</th>
    </tr>
  </thead>
  <tbody>
    <% @drafts.each do |draft| %>
      <% if draft.complete? %>
        <tr class="success">
      <% else %>
        <tr>
      <% end %>
        <td><%= draft.round %></td>
        <td><%= draft.pick %></td>
        <td><%= link_to draft.team.name, draft.team %></td>
        <td>
          <% if draft.player.nil? %>
            <i>In progress</i>
          <% else %>
            <%= draft.player.name %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/results/round.html.erb
<h1>Results for Round <%= params[:round] %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Round</th>
      <th>Pick</th>
      <th>Team</th>
      <th>Player</th>
    </tr>
  </thead>
  <tbody>
    <% @drafts.each do |draft| %>
      <% if draft.complete? %>
        <tr class="success">
      <% else %>
        <tr>
      <% end %>
        <td><%= draft.round %></td>
        <td><%= draft.pick %></td>
        <td><%= link_to draft.team.name, draft.team %></td>
        <td>
          <% if draft.player.nil? %>
            <i>In progress</i>
          <% else %>
            <%= draft.player.name %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/welcome/index.html.erb
<h1 style="text-align: center">Welcome to the NFL Draft</h1>